name: Deploy Bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  sync_to_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove config.json
        uses: JesseTG/rm@v1.0.0
        with:
          path: config.json

      - name: Deploy files
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avz
          path: ./
          remote_path: ${{ secrets.DEPLOY_PATH }}/${{ github.ref_name }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Restart service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: sudo systemctl restart aredl-manager-main
